services:
  cache:
    image: busybox
    tty: true
    volumes:
      - /npm_cache
  app:
    build:
      context: .
      dockerfile: Dockerfile.starter
    ports:
      - "3000:3000"
    volumes:
      - .:/work
    volumes_from:
      - cache
